# Generated by Django 5.2.5 on 2025-08-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_postmodel_author_postmodel_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ("-date_created",)},
        ),
    ]
