# Generated by Django 5.2.7 on 2025-10-29 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profilemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="image",
            field=models.ImageField(
                default="Default-Icon.jpg",
                upload_to="profile",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg"])
                ],
            ),
        ),
    ]
